//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenII_Lenguajes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBExamenContext1 : DbContext
    {
        public DBExamenContext1()
            : base("name=DBExamenContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCurso> tbCurso { get; set; }
        public virtual DbSet<tbEstudiante> tbEstudiante { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
    }
}
